### ISSUE TITLE
Error in alert.js:89 "TypeError: 'undefined' is not a function"

### ISSUE THREAD

**Issue by lucianghinda** [metaskills/less-rails-bootstrap#28]
Hi,

I'm having the following Javascript error:
TypeError: 'undefined' is not a function (evaluating '$('body').on('click.alert.data-api', dismiss, Alert.prototype.close)') 
in alert.js:89

My application.js looks like this:

``` javascript
//= require jquery
//= require jquery_ujs
//= require jwysiwyg/jquery.wysiwyg.js
//= require_tree .
//= require twitter/bootstrap
```

I've tried removing require_tree or removing jwysiwyg and still the same error.  

If I remove alert.js, then I receive another similar error with the next button.js:96

TypeError: 'undefined' is not a function (evaluating '$('body').on('click.button.data-api', '[data-toggle^=button]', function ( e ) {
      $(e.target).button('toggle')
    })')

I'm not so experimented with Rails 3.1.0 or Twitter Bootstrap but the project I'm working on is standard rails 3.1.0 project.

Gems list:
less (2.0.9)
less-rails (2.1.5)
less-rails-bootstrap (2.0.3)
rails (3.1.0)
